version: "3"
services:

  webserver:
    build:
      context: ./docker/apache
    restart: 'always'
    ports:
      - "80:80"
      - "5173:5173"
      - "443:443"
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT}:/project:delegated
      - ${PHP_INI}:/usr/local/etc/php/php.ini:cached
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled:cached
      - ${APACHE_LOG_DIR}:/var/log/apache2:cached
      - ${CERTIFICATES}:/etc/apache2/ssl:cached
      - ${CRONJOB_DIR}:/etc/cron.d:cached
      - ${SUPERVISOR_DIR}:/etc/supervisor/conf.d:cached
      - ${SESSIONS_DIR}:/sessions:cached
      - ${COMPOSER_AUTH}:/root/.composer:cached
    environment:
      - TZ=Europe/Amsterdam
      - COMPOSER_MEMORY_LIMIT=-1
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}

  mysql:
    build:
      context: ./docker/mysql
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
