FROM mysql:latest
MAINTAINER Michael Aben <m.aben@live.nl>

CMD mysql --default-authentication-plugin=mysql_native_password
CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci", "--skip-character-set-client-handshake"]